export const CHANGE_IMG_LANDING = "CHANGE_IMG_LANDING";
export const GET_ALL_POKEMONS = "GET_ALL_POKEMONS";
export const GET_POKEMON_BY_ID = "GET_POKEMONS_BY_ID";
export const PAGINADO_POKEMONS = "PAGINADO_POKEMONS";
export const NEXT_PREVIUS = "NEXT_PREVIUS";
